name: upper Build

on:
  push:
    paths: 
      - ".github/workflow/upper-buils.yml"
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run:  go version
      - run: pwd && ls -ltrh
